### ISSUE TITLE
daily average shows total cards done

### ISSUE THREAD

**Issue by Sharmin126** [glutanimate/review-heatmap#50] opened 2019-11-30 15:12 UTC
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've checked if anyone else asked this question before by looking through the issue reports.

#### Your question

my daily average shows the total number of cards I've done altogether instead of an average across the days I've studied, how do I fix this? (med student with zero programming experience)

**Comment by glutanimate** [comment] 2020-04-30 13:33
Hi Sharmin,

I just pushed a [new beta release](https://github.com/glutanimate/review-heatmap/releases/v1.0.0-beta.1) that should fix this (among other things). Please give it a try and let me know if it works for you.

Closing this as a duplicate of #40 for now.

**Closed by glutanimate** 2020-04-30 13:33 UTC
Labels: question
