### ISSUE TITLE
Collision with Stats Plus Add-on

### ISSUE THREAD

**Issue by agentca** [glutanimate/review-heatmap#149] opened 2022-05-05 22:54 UTC
#### Problem description:
As stated in title. How review heatmap appears in my Anki:

<img width="822" alt="image" src="https://user-images.githubusercontent.com/105023285/167038692-c5a020c6-a369-4f91-bcdf-6233c58df66c.png">

#### Checklist
 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up:
    
    Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
    Platform: Mac 10.16
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2022-05-04 18:15:56
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['popup_dictionary', 0, 'None', mod]
    '' ['put_ALL_due_learning_cards_first', 0, 'None', '']
    AMBOSS add-on ['0amboss_addon', 2022-01-19T14:42, 'None', '']
    Add Hyperlink ['318752047', 2021-11-21T10:04, 'None', '']
    Additional Card Fields Fork for 21 ['744725736', 2022-02-21T16:22, 'None', mod]
    Advanced Browser ['874215009', 2022-01-30T17:07, 'None', '']
    AnKing Note Types Easy Customization ['952691989', 2022-03-29T11:30, 'None', mod]
    Anki Simulator ['817108664', 2021-08-07T14:24, 'None', '']
    Anki Zoom ['538879081', 2020-04-03T19:20, 'v1.1.3', '']
    Batch Editing ['291119185', 2019-09-19T12:04, 'None', '']
    BetterSearch ['1052724801', 2021-11-21T12:42, 'None', '']
    Browser Resizer ['1435775540', 2021-08-01T16:11, 'None', '']
    Browser TableEditor side-by-side horizontal split ['831846358', 2022-01-25T16:11, 'None', mod]
    Card browser List only one card per note ['797076357', 2020-08-10T23:23, 'None', mod]
    Clickable Tags v20 ['1739176371', 2022-01-30T16:58, 'None', '']
    Collapsible Fields ['1896168623', 2021-08-28T16:45, 'None', '']
    Convert Subdecks to Tag Hierarchy ['1172858842', 2020-02-23T16:03, 'None', '']
    Create Filtered Deck from the Browser ['861263371', 2017-08-29T13:57, 'None', '']
    Custom Background Image and Gear Icon ['1210908941', 2022-04-10T10:30, 'None', mod]
    Customize Keyboard Shortcuts ['24411424', 2022-04-14T23:52, 'None', mod]
    Edit Field During Review Cloze ['385888438', 2022-02-21T23:35, '6.11', mod]
    Extended Card Stats During Review ['1008566916', 2017-08-29T13:59, 'None', '']
    Extended Tag AddEdit Dialog ['1135507717', 2022-03-13T05:41, 'None', '']
    Fastbar- with nightmode support ['46611790', 2022-04-14T22:04, 'None', '']
    Free Weekend - or Any Other Day ['742185195', 2020-04-10T06:57, 'None', mod]
    Hierarchical Tags 2 ['594329229', 2021-03-06T20:25, 'None', '']
    High Yield Tags ['1918380616', 2021-08-06T19:48, 'None', '']
    Highlight Search Results in the Browser ['225180905', 2021-03-10T11:06, 'None', '']
    Hint Hotkeys ['1844908621', 2019-02-26T12:58, 'None', '']
    Image Editor ['307397307', 2021-12-19T05:58, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-27T21:21, 'None', '']
    Image Style Editor ['1593969147', 2021-12-17T01:01, 'None', mod]
    ImageResizer ['1214357311', 2022-03-25T22:18, 'None', '']
    Learning Step and Review Interval Retention ['1949865265', 2022-03-14T15:58, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2021-01-27T03:09, 'None', mod]
    More Overview Stats 21 ['738807903', 2021-07-30T14:13, 'None', mod]
    Placeholder- Pomodoro-like Study Timer ['907028815', 2022-03-04T10:59, 'None', '']
    Pokemanki ['633922407', 2021-02-24T12:49, 'None', '']
    Progress Bar ['2091361802', 2019-03-02T20:27, 'None', '']
    Quick Colour Changing ['2491935955', 2019-03-02T20:26, 'None', mod]
    Rebuild All  Empty All for Anki 21 ['1810938259', 2018-07-19T23:40, 'None', '']
    Refocus Card when Reviewing 21 ['1642550423', 2019-03-04T12:20, 'None', '']
    Resize images in editor ['1103084694', 2021-07-19T01:35, 'None', mod]
    Review Heatmap ['review_heatmap', 2020-04-30T08:23, 'None', '']
    Special Fields ['1102281552', 2022-02-23T11:27, 'None', mod]
    Speed Focus Mode auto-alert auto-reveal auto-fail/good ['1046608507', 2019-06-02T04:11, 'None', '']
    Stats Plus ['1009670238', 2021-03-04T06:23, 'None', '']
    Straight Reward ['957961234', 2021-01-11T06:37, 'None', '']
    Symbols As You Type ['2040501954', 2021-03-21T21:17, 'None', '']
    Symbols ['1461102936', 2019-04-23T08:37, 'None', mod]
    The KING of Button Add-ons ['374005964', 2020-04-17T17:33, 'None', mod]
    Web Browser - Search terms Import texts and images automatically ['864545277', 2022-01-17T15:33, 'None', mod]
    Ze Frozen Fields ['94610912', 2021-02-11T18:06, 'None', '']
    add-on dialog searchfilter bar ['561945101', 2021-12-05T14:28, 'None', '']
    when is next learning card due today due ['563204849', 2021-12-06T09:06, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    1008566916 1009670238 1046608507 1052724801 1102281552 1103084694 1135507717 1172858842 1210908941 1214357311 1374772155 1435775540 1461102936 1556734708 1593969147 1642550423 1739176371 1810938259 1844908621 1896168623 1918380616 1949865265 2040501954 2091361802 225180905 24411424 2491935955 291119185 307397307 318752047 374005964 385888438 46611790 538879081 561945101 563204849 594329229 633922407 738807903 742185195 744725736 797076357 817108664 831846358 861263371 864545277 874215009 907028815 94610912 952691989 957961234
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Legacy ReMemorize Rescheduler with sibling and logging v142 ['323586997', 2020-11-19T23:27, 'None', mod]
    Load Balanced Scheduler ['208879074', 2019-07-23T21:37, 'None', '']
    Mini Format Pack ['295889520', 2019-03-01T21:13, 'None', '']
    Picmonic Anki Add-On ['40737180', 2021-09-29T13:58, 'None', '']
    Puppy Reinforcement ['puppy_reinforcement', 2020-02-05T01:16, 'None', '']
    Reset Ease ['947935257', 2020-12-27T08:59, 'None', '']
    Syllabus - Anki Statistics and Export by Tag and Deck ['668156440', 2020-01-19T13:52, 'None', mod]
    Wrapper meta-addon ['396502676', 2022-03-29T17:01, 'None', '']

#### Error message (if any)

N/A

**Comment by glutanimate** [comment] 2022-05-18 17:30
Hey agentca,

Thanks for the report! I just released an update for Review Heatmap [over on AnkiWeb](https://ankiweb.net/shared/info/1771074083) (you can install it directly there, no need to manually download the release off of GitHub). Would you mind giving the update a try and letting me know if it fixes things for you?

Thanks in advance!

**Comment by kguy18** [comment] 2022-05-19 15:19
@glutanimate I am having the same issue, I deleted the old add-on and then used the AnkiWeb code to reinstall it and I am getting the exact same issue posted here. I also downloaded the latest 2.1.52 QT6 for M1 Macs and it broke a bunch of other add-ons so I reverted back to 2.1.49 and everything seems to be working except Review Heatmap. Is there any other info I can provide to help with troubleshooting?

**Comment by glutanimate** [comment] 2022-05-19 15:41
@kguy18 could you try disabling all other add-ons and see if the issue persists after restarting Anki? If that doesn't help, would you mind sending me your Anki debug info? You can do so by heading to Anki → About, clicking on "Copy Debug Info", and then pasting the contents here.

**Comment by glutanimate** [comment] 2022-05-19 16:11
@kguy18 if you have time, it might also be worth to go with the full debug procedure listed [here](https://github.com/glutanimate/review-heatmap/issues/151) straight away as that would hopefully provide me with everything I need to try to replicate the issue locally (the linked issue is about timezone-related bugs, which I don't think are the cause here, but the same type of debug info would be helpful to investigate this problem as well).

**Comment by kguy18** [comment] 2022-05-19 20:55
@glutanimate Yep it was an additional add-on conflict, which it appears based on the comments is a know issue on their add-on page (https://ankiweb.net/shared/info/1009670238) maybe the original issue will be resolved by disabling the "Stats Plus" add-on. Its a bummer because I like your heat map better, though I also like all the additional information shown in Stats Plus. Thanks for taking the time to reply to the issue!

**Comment by glutanimate** [comment] 2022-05-22 09:39
@kguy18 thanks for digging into this! Can reproduce the conflict here (though had to go to 2.1.49 as Stats Plus has a few issues on 2.1.50 unrelated to RH).

I pushed a workaround in #155 that should address the conflict (thanks also to @swerage for looking into this in #133). Would you mind giving the [PR test build](https://github.com/glutanimate/temp-workspace/releases/download/0.0.1/review-heatmap-v1.0.0-11-gd689982-qt5+qt6.ankiaddon) a try and letting me know if it works for you?

**Comment by kguy18** [comment] 2022-05-22 14:11
@glutanimate just tested it and the conflict is resolved, works with and without Stats Plus enabled, thanks for a quick turnaround! I tested on Version ⁨2.1.49 (dc80804a)⁩, MacOS.

**Comment by glutanimate** [comment] 2022-05-22 14:34
@kguy18 thanks for giving it a try, happy to hear that! Will merge the changes then and mark this resolved. The fix should land in the v1.0.1 AnkiWeb update.

**Closed** 2022-05-22 14:34 UTC
Labels: add-on conflict
